apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: palm
  name: palm
  namespace: default
spec:
  selector:
    matchLabels:
      app: palm
      version: v1
  template:
    metadata:
      labels:
        app: palm
        version: v1
    spec:
      containers:
      - image: gcr.io/github-webhook-196021/palm:e9463a3d8c8ab9e5b9e57a4b9ee9930b63ed3f0d
        name: palm
        ports:
        - containerPort: 80
