apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: palm
  name: palm
  namespace: default
spec:
  selector:
    matchLabels:
      app: palm
      version: v1
  template:
    metadata:
      labels:
        app: palm
        version: v1
    spec:
      containers:
      - image: gcr.io/github-webhook-196021/palm:121677fab670d9b4719c0234d98055ea88d242e7
        name: palm
        ports:
        - containerPort: 80
