apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: palm
  name: palm
  namespace: default
spec:
  selector:
    matchLabels:
      app: palm
      version: v1
  template:
    metadata:
      labels:
        app: palm
        version: v1
    spec:
      containers:
      - image: gcr.io/github-webhook-196021/palm:9d59237840f9cb521d9aba88b124a53bca0dcffa
        name: palm
        ports:
        - containerPort: 80
