apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: palm
  name: palm
  namespace: default
spec:
  selector:
    matchLabels:
      app: palm
      version: v1
  template:
    metadata:
      labels:
        app: palm
        version: v1
    spec:
      containers:
      - image: gcr.io/github-webhook-196021/palm:5bd1149a4110e2fdd566a1cdafd9c7dd017be43d
        name: palm
        ports:
        - containerPort: 80
